name: smap_io
channels:
- conda-forge
dependencies:
- netcdf4=1.2.2
- numpy
- h5py
- pandas
- pyresample
- pip:
  - datedown
  - ease-grid
  - pygeobase
  - pygeogrids
  - pytesmo
  - repurpose
  - trollsift==0.2.1

